# Generated by Django 2.1.7 on 2019-03-17 17:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(help_text='Word to display on card.', max_length=50, verbose_name='word')),
                ('bucket', models.SmallIntegerField(default=0, help_text='Card play progress.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='bin')),
                ('wrong_count', models.SmallIntegerField(default=0, help_text='Lifetime wrong count.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='wrong count')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Card last review date/time.', null=True, verbose_name='reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('user', models.ForeignKey(help_text='User that owns this card.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
